"""empty message

Revision ID: 11e585a3acfd
Revises: 780d0ae65f7f
Create Date: 2025-01-27 22:04:25.627117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11e585a3acfd'
down_revision = '780d0ae65f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('zoning', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('improvement_value', sa.Float(), nullable=True),
    sa.Column('land_value', sa.Float(), nullable=True),
    sa.Column('parcel_value', sa.Float(), nullable=True),
    sa.Column('mail_address', sa.String(), nullable=True),
    sa.Column('mail_city', sa.String(), nullable=True),
    sa.Column('mail_state', sa.String(), nullable=True),
    sa.Column('mail_zip', sa.String(), nullable=True),
    sa.Column('mail_country', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('building_SQFT', sa.Float(), nullable=True),
    sa.Column('building_count', sa.Integer(), nullable=True),
    sa.Column('legal_description', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('acre', sa.Float(), nullable=True),
    sa.Column('acre_sqft', sa.Float(), nullable=True),
    sa.Column('fema_flood_zone', sa.String(), nullable=True),
    sa.Column('property_status', sa.String(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_number')
    )
    op.drop_table('property')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parcel_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('year_built', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('building_SQFT', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('building_count', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('acre', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('acre_sqft', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mail_address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('mail_city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mail_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mail_zip', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('mail_country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('improvement_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('land_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('parcel_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('zoning', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('county', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('legal_description', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('fema_flood_zone', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='property_pkey')
    )
    op.drop_table('properties')
    # ### end Alembic commands ###
