"""empty message

Revision ID: 16fefb61fb18
Revises: 6e0e0dd31bc3
Create Date: 2025-01-16 16:27:14.462361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fefb61fb18'
down_revision = '6e0e0dd31bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building_SQFT', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('building_count', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('legal_description', sa.String(length=180), nullable=True))
        batch_op.add_column(sa.Column('fema_flood_zone', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('block', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('block')
        batch_op.drop_column('fema_flood_zone')
        batch_op.drop_column('legal_description')
        batch_op.drop_column('state')
        batch_op.drop_column('county')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('building_count')
        batch_op.drop_column('building_SQFT')

    # ### end Alembic commands ###
