"""empty message

Revision ID: 4bde8cfbf0ba
Revises: 81301cd216b9
Create Date: 2025-01-07 16:33:05.902261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bde8cfbf0ba'
down_revision = '81301cd216b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Filename', sa.String(length=255), nullable=False),
    sa.Column('Acres', sa.String(length=255), nullable=True),
    sa.Column('County', sa.String(length=255), nullable=True),
    sa.Column('Owner', sa.String(length=255), nullable=True),
    sa.Column('Parcel', sa.String(length=255), nullable=True),
    sa.Column('Range', sa.String(length=255), nullable=True),
    sa.Column('Section', sa.String(length=255), nullable=True),
    sa.Column('StartingBid', sa.String(length=255), nullable=True),
    sa.Column('State', sa.String(length=255), nullable=True),
    sa.Column('Township', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('file_row')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_row',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('Acres', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('County', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Parcel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Range', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('StartingBid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('State', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('Township', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='file_row_pkey')
    )
    op.drop_table('files')
    # ### end Alembic commands ###
