"""empty message

Revision ID: 6e0e0dd31bc3
Revises: ecd4724fa9f9
Create Date: 2025-01-15 22:05:43.497385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e0e0dd31bc3'
down_revision = 'ecd4724fa9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('zoning', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('improvement_value', sa.Float(), nullable=True),
    sa.Column('land_value', sa.Float(), nullable=True),
    sa.Column('parcel_value', sa.Float(), nullable=True),
    sa.Column('mail_address', sa.String(length=200), nullable=True),
    sa.Column('mail_city', sa.String(length=50), nullable=True),
    sa.Column('mail_state', sa.String(length=50), nullable=True),
    sa.Column('mail_zip', sa.String(length=20), nullable=True),
    sa.Column('mail_country', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('acre', sa.Float(), nullable=True),
    sa.Column('acre_sqft', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
