"""empty message

Revision ID: 81301cd216b9
Revises: 1f78ad6d3704
Create Date: 2025-01-07 16:24:47.031803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81301cd216b9'
down_revision = '1f78ad6d3704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Filename', sa.String(length=255), nullable=False),
    sa.Column('Acres', sa.String(length=255), nullable=True),
    sa.Column('County', sa.String(length=255), nullable=True),
    sa.Column('Owner', sa.String(length=255), nullable=True),
    sa.Column('Parcel', sa.String(length=255), nullable=True),
    sa.Column('Range', sa.String(length=255), nullable=True),
    sa.Column('Section', sa.String(length=255), nullable=True),
    sa.Column('StartingBid', sa.String(length=255), nullable=True),
    sa.Column('State', sa.String(length=255), nullable=True),
    sa.Column('Township', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_row')
    # ### end Alembic commands ###
