"""empty message

Revision ID: d1616aa2e15b
Revises: e8f07742034d
Create Date: 2025-01-28 12:59:13.384356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1616aa2e15b'
down_revision = 'e8f07742034d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('property_status')
        batch_op.drop_column('notes')
        batch_op.drop_column('property_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_status', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
