"""empty message

Revision ID: d57b12220711
Revises: 4bde8cfbf0ba
Create Date: 2025-01-15 19:44:05.912031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57b12220711'
down_revision = '4bde8cfbf0ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parcel_number', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('zoning', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('improvement_value', sa.Float(), nullable=True),
    sa.Column('land_value', sa.Float(), nullable=True),
    sa.Column('parcel_value', sa.Float(), nullable=True),
    sa.Column('mail_address', sa.String(length=255), nullable=True),
    sa.Column('mail_city', sa.String(length=100), nullable=True),
    sa.Column('mail_state', sa.String(length=50), nullable=True),
    sa.Column('mail_zip', sa.String(length=20), nullable=True),
    sa.Column('mail_country', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('acre', sa.Float(), nullable=True),
    sa.Column('acre_sqft', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parcel_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcel')
    # ### end Alembic commands ###
