"""empty message

Revision ID: ecd4724fa9f9
Revises: 76626fec3913
Create Date: 2025-01-15 21:08:51.541047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd4724fa9f9'
down_revision = '76626fec3913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Acres', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('County', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Range', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Section', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('StartingBid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('State', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Township', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('Filename', sa.String(length=255), nullable=False))
        batch_op.drop_column('Address')
        batch_op.drop_column('MailCountry')
        batch_op.drop_column('LandVal')
        batch_op.drop_column('Zoning')
        batch_op.drop_column('ImprovVal')
        batch_op.drop_column('YearBuilt')
        batch_op.drop_column('Lon')
        batch_op.drop_column('ParVal')
        batch_op.drop_column('Lat')
        batch_op.drop_column('MailZip')
        batch_op.drop_column('MailAdd')
        batch_op.drop_column('MailCity')
        batch_op.drop_column('MailState')
        batch_op.drop_column('LL_GisAcre')
        batch_op.drop_column('LL_GisSqFt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('LL_GisSqFt', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LL_GisAcre', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MailState', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MailCity', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MailAdd', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MailZip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Lat', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ParVal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Lon', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('YearBuilt', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ImprovVal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Zoning', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('LandVal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('MailCountry', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('Filename')
        batch_op.drop_column('Township')
        batch_op.drop_column('State')
        batch_op.drop_column('StartingBid')
        batch_op.drop_column('Section')
        batch_op.drop_column('Range')
        batch_op.drop_column('County')
        batch_op.drop_column('Acres')

    # ### end Alembic commands ###
