"""empty message

Revision ID: f305fd29a49c
Revises: d1616aa2e15b
Create Date: 2025-01-29 13:35:24.788981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f305fd29a49c'
down_revision = 'd1616aa2e15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_data', sa.JSON(), nullable=True))
        batch_op.drop_column('dynamic_fields')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dynamic_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_data')

    # ### end Alembic commands ###
